<?xml version="1.0"?>
<package format="3">
  <name>ros2_day2_hw3</name>
  <version>0.1.0</version>
  <description>
     과제 3 - QThread 기반 다중 토픽 모니터링 대시보드
  </description>
  <maintainer email="author@mail.com">author</maintainer>
  <author>author</author>
  <license>BSD</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
